"""MCP Server for Obsidian Second Mind.

v1.2.0: GitHub Radar + Context Packer.
- GitHub Radar: scan_github_trending, watch_developer, analyze_repo tools
- Context Packer: pack_context tool (project → single .md for AI)

v1.1.0: Auto Architect — scan_architecture tool (code → Mermaid diagrams).

v1.0.0: Ultimate Brain (release).
- Path traversal protection on get_note / update_note
- Settings caching with lru_cache

v0.9.0: Agent Memory.

v0.8.0: Temporal Brain.
- Temporal KG: kg_add_fact, kg_invalidate, kg_timeline tools
- Contradiction detection: kg_check_contradictions tool

v0.7.0: Cascade Intelligence.
- Cascade ingest: ingest_source tool (one source → N wiki updates)
- Auto radar: auto_radar_scan tool (diff-based scanning + Telegram alerts)

v0.6.0: Capture & Recall.
- Wake-up context: get_wakeup_context tool (~200 token critical facts summary)
- Query write-back: save_insight tool (save valuable answers back to wiki)
- Telegram capture bot integration (separate module)

v0.5.0: Intelligence Layer.
- Session Intelligence: analyze_sessions tool (repeating problems, workarounds)
- Tech Radar: scout_tools tool (new MCP servers, AI tools, devtools)
- Dependency Watch: check_dependencies tool (outdated packages, security patches)

v0.4.0: Adaptive Brain.
- Knowledge graph: query_graph tool (neighbors, paths, hubs, clusters)
- Pattern extraction: extract_patterns tool (auto-rules from decision outcomes)
- Decay scoring in search (fresh notes rank higher)
- Enhanced watcher hooks (auto-logging, index.md regeneration)
"""
import json
import logging
from datetime import date, datetime
from pathlib import Path

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import (
    Resource,
    TextContent,
    Tool,
)

from obsidian_bridge.config import get_settings
from obsidian_bridge.indexer import VaultIndex
from obsidian_bridge.parser import get_project_notes, get_projects, parse_note

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Server setup
# ---------------------------------------------------------------------------

app = Server("obsidian-second-mind")


def _get_index() -> VaultIndex:
    """Lazy-init the vault index."""
    if not hasattr(_get_index, "_instance"):
        settings = get_settings()
        _get_index._instance = VaultIndex(settings)
    return _get_index._instance


def _get_vault_path() -> Path:
    return get_settings().vault_path


# ---------------------------------------------------------------------------
# Vault Meta-Files: index.md + log.md (Karpathy Pattern)
# ---------------------------------------------------------------------------

def _regenerate_index(vault: Path):
    """Regenerate index.md — catalog of all pages in the vault.

    Karpathy: 'index.md is content-oriented. It's a catalog of everything
    in the wiki — each page listed with a link, a one-line summary.'
    """
    today = date.today().isoformat()
    projects = get_projects(vault)

    lines = [
        "# 📚 Vault Index",
        f"> Auto-generated by Obsidian Second Mind. Last updated: {today}",
        "",
    ]

    # Global rules
    global_dir = vault / "_global"
    if global_dir.exists():
        global_notes = sorted(global_dir.rglob("*.md"))
        lines.append(f"## 🌐 Global Rules ({len(global_notes)})")
        lines.append("")
        for md in global_notes:
            note = parse_note(md, vault)
            if note:
                rel = md.relative_to(vault)
                lines.append(f"- [{note.title}]({rel}) — {note.note_type}")
        lines.append("")

    # Per-project sections
    total_notes = 0
    for project in projects:
        notes = get_project_notes(vault, project)
        if not notes:
            continue
        total_notes += len(notes)

        # Sort by type for consistent ordering
        type_order = {"prd": 0, "architecture": 1, "guidelines": 2, "api": 3,
                      "decision": 4, "concept": 5, "comparison": 6,
                      "synthesis": 7, "research": 8, "note": 9}
        notes.sort(key=lambda n: type_order.get(n.note_type, 99))

        types_list = ", ".join(sorted(set(n.note_type for n in notes)))
        lines.append(f"## 📁 {project} ({len(notes)} notes: {types_list})")
        lines.append("")
        for note in notes:
            rel = note.path
            # Extract first meaningful line as summary
            summary = _extract_summary(note.content)
            lines.append(f"- [{note.title}]({rel}) `{note.note_type}` — {summary}")
        lines.append("")

    # Stats
    lines.extend([
        "---",
        "## 📊 Stats",
        f"- Total projects: {len(projects)}",
        f"- Total notes: {total_notes}",
        f"- Last updated: {today}",
    ])

    index_path = vault / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Index regenerated: {total_notes} notes across {len(projects)} projects")


def _extract_summary(content: str, max_length: int = 80) -> str:
    """Extract a one-line summary from note content."""
    for line in content.split("\n"):
        line = line.strip()
        # Skip headings, empty lines, frontmatter
        if not line or line.startswith("#") or line.startswith("---"):
            continue
        # Skip metadata-like lines
        if line.startswith(">") or line.startswith("- **") or line.startswith("| "):
            continue
        # Clean up and truncate
        summary = line[:max_length]
        if len(line) > max_length:
            summary = summary.rsplit(" ", 1)[0] + "…"
        return summary
    return "(no summary)"


def _append_to_log(
    vault: Path,
    operation: str,
    project: str = "",
    title: str = "",
    note_type: str = "",
    tags: list[str] | None = None,
    details: str = "",
):
    """Append entry to log.md — chronological operation log.

    Karpathy: 'log.md is chronological. It's an append-only record of what
    happened and when — ingests, queries, lint passes.'
    """
    today = date.today().isoformat()
    now = datetime.now().strftime("%H:%M")

    log_path = vault / "log.md"

    # Create file with header if it doesn't exist
    if not log_path.exists():
        log_path.write_text(
            "# 📋 Vault Log\n"
            "> Chronological record of vault operations. Append-only.\n\n",
            encoding="utf-8",
        )

    # Build log entry
    parts = [f"## [{today} {now}] {operation}"]
    if project:
        parts[0] += f" | {project}"
    if title:
        parts[0] += f" | {title}"
    if note_type:
        parts.append(f"Type: {note_type}")
    if tags:
        parts.append(f"Tags: {', '.join(tags)}")
    if details:
        parts.append(details)
    parts.append("")  # Empty line after entry

    # Append to log
    with open(log_path, "a", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")

    logger.info(f"Log entry: {operation} | {project} | {title}")


# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------

@app.list_resources()
async def list_resources() -> list[Resource]:
    vault = _get_vault_path()
    projects = get_projects(vault)

    resources = [
        Resource(
            uri="vault://global",
            name="Global Rules & Standards",
            description="Global coding standards, tech stack, and design principles",
            mimeType="text/markdown",
        ),
        Resource(
            uri="vault://projects",
            name="All Projects",
            description="List of all projects in the vault",
            mimeType="application/json",
        ),
        Resource(
            uri="vault://index",
            name="Vault Index",
            description="Auto-generated catalog of all wiki pages",
            mimeType="text/markdown",
        ),
        Resource(
            uri="vault://log",
            name="Vault Log",
            description="Chronological operation log",
            mimeType="text/markdown",
        ),
    ]

    for project in projects:
        resources.append(Resource(
            uri=f"vault://project/{project}",
            name=f"Project: {project}",
            description=f"All notes for project '{project}'",
            mimeType="text/markdown",
        ))

    return resources


@app.read_resource()
async def read_resource(uri: str) -> str:
    vault = _get_vault_path()

    if uri == "vault://global":
        global_dir = vault / "_global"
        if not global_dir.exists():
            return "No global notes found."
        notes = []
        for md in sorted(global_dir.rglob("*.md")):
            note = parse_note(md, vault)
            if note:
                notes.append(f"# {note.title}\n\n{note.content}")
        return "\n\n---\n\n".join(notes)

    elif uri == "vault://projects":
        projects = get_projects(vault)
        result = {"projects": []}
        for p in projects:
            notes = get_project_notes(vault, p)
            result["projects"].append({
                "name": p,
                "notes_count": len(notes),
                "types": list(set(n.note_type for n in notes)),
            })
        return json.dumps(result, indent=2)

    elif uri == "vault://index":
        index_path = vault / "index.md"
        if index_path.exists():
            return index_path.read_text(encoding="utf-8")
        return "index.md not yet generated. Call create_note or rebuild_index to generate it."

    elif uri == "vault://log":
        log_path = vault / "log.md"
        if log_path.exists():
            return log_path.read_text(encoding="utf-8")
        return "log.md not yet created. Operations will be logged here automatically."

    elif uri.startswith("vault://project/"):
        project = uri.replace("vault://project/", "")
        notes = get_project_notes(vault, project)
        if not notes:
            return f"No notes found for project '{project}'."
        parts = []
        for note in notes:
            parts.append(f"## {note.title}\n**Type**: {note.note_type} | **Tags**: {', '.join(note.tags)}\n\n{note.content}")
        return "\n\n---\n\n".join(parts)

    return f"Unknown resource: {uri}"


# ---------------------------------------------------------------------------
# Tools — dispatch dict
# ---------------------------------------------------------------------------

def _build_all_handlers() -> dict:
    """Collect handlers from all tool modules."""
    from obsidian_bridge.mcp_tools import notes, maintenance, scout_tools, capture, temporal, memory, radar
    handlers = {}
    for mod in (notes, maintenance, scout_tools, capture, temporal, memory, radar):
        handlers.update(mod.HANDLERS)
    return handlers


def _build_all_tools() -> list[Tool]:
    """Collect Tool definitions from all modules in canonical order."""
    from obsidian_bridge.mcp_tools import notes, maintenance, scout_tools, capture, temporal, memory, radar
    result = []
    for mod in (notes, maintenance, scout_tools, capture, temporal, memory, radar):
        result.extend(mod.TOOLS)
    return result


# Lazy-initialised at first call to avoid import-time side effects
_ALL_HANDLERS: dict | None = None


def _get_all_handlers() -> dict:
    global _ALL_HANDLERS
    if _ALL_HANDLERS is None:
        _ALL_HANDLERS = _build_all_handlers()
    return _ALL_HANDLERS


@app.list_tools()
async def list_tools() -> list[Tool]:
    return _build_all_tools()


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    handler = _get_all_handlers().get(name)
    if not handler:
        return [TextContent(type="text", text=f"Unknown tool: {name}")]
    return await handler(arguments)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def run_server():
    """Run the MCP server via stdio."""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())


def main():
    """CLI entry point for the MCP server."""
    import asyncio
    asyncio.run(run_server())


if __name__ == "__main__":
    main()
