"""MCP Server for Obsidian Second Mind.

v1.1.0: Auto Architect — scan_architecture tool (code → Mermaid diagrams).

v1.0.0: Ultimate Brain (release).
- Path traversal protection on get_note / update_note
- Settings caching with lru_cache

v0.9.0: Agent Memory.

v0.8.0: Temporal Brain.
- Temporal KG: kg_add_fact, kg_invalidate, kg_timeline tools
- Contradiction detection: kg_check_contradictions tool

v0.7.0: Cascade Intelligence.
- Cascade ingest: ingest_source tool (one source → N wiki updates)
- Auto radar: auto_radar_scan tool (diff-based scanning + Telegram alerts)

v0.6.0: Capture & Recall.
- Wake-up context: get_wakeup_context tool (~200 token critical facts summary)
- Query write-back: save_insight tool (save valuable answers back to wiki)
- Telegram capture bot integration (separate module)

v0.5.0: Intelligence Layer.
- Session Intelligence: analyze_sessions tool (repeating problems, workarounds)
- Tech Radar: scout_tools tool (new MCP servers, AI tools, devtools)
- Dependency Watch: check_dependencies tool (outdated packages, security patches)

v0.4.0: Adaptive Brain.
- Knowledge graph: query_graph tool (neighbors, paths, hubs, clusters)
- Pattern extraction: extract_patterns tool (auto-rules from decision outcomes)
- Decay scoring in search (fresh notes rank higher)
- Enhanced watcher hooks (auto-logging, index.md regeneration)
"""
import json
import logging
from datetime import date, datetime
from pathlib import Path

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import (
    Resource,
    TextContent,
    Tool,
)

from obsidian_bridge.config import get_settings
from obsidian_bridge.indexer import VaultIndex
from obsidian_bridge.linter import VaultLinter
from obsidian_bridge.parser import get_project_notes, get_projects, parse_note, scan_vault
from obsidian_bridge.patterns import PatternExtractor
from obsidian_bridge.scout import DependencyChecker, SessionAnalyzer, TechRadar
from obsidian_bridge.wakeup import WakeupContext
from obsidian_bridge.ingest import IngestPipeline, IngestSource
from obsidian_bridge.auto_radar import AutoRadar, notify_telegram as radar_notify
from obsidian_bridge.architect import scan_and_save as scan_architecture
from obsidian_bridge.graph import (
    KnowledgeGraph,
    TemporalKnowledgeGraph,
    ContradictionDetector,
)
from obsidian_bridge.fact_extractor import FactExtractor
from obsidian_bridge.hooks import SessionHooks, generate_enhanced_wakeup

logger = logging.getLogger(__name__)

# All supported note types (extended for Wiki Pattern)
NOTE_TYPES = [
    "prd", "architecture", "guidelines", "api", "decision", "note",
    "concept", "comparison", "synthesis", "research",
]

# ---------------------------------------------------------------------------
# Server setup
# ---------------------------------------------------------------------------

app = Server("obsidian-second-mind")


def _get_index() -> VaultIndex:
    """Lazy-init the vault index."""
    if not hasattr(_get_index, "_instance"):
        settings = get_settings()
        _get_index._instance = VaultIndex(settings)
    return _get_index._instance


def _get_vault_path() -> Path:
    return get_settings().vault_path


# ---------------------------------------------------------------------------
# Vault Meta-Files: index.md + log.md (Karpathy Pattern)
# ---------------------------------------------------------------------------

def _regenerate_index(vault: Path):
    """Regenerate index.md — catalog of all pages in the vault.

    Karpathy: 'index.md is content-oriented. It's a catalog of everything
    in the wiki — each page listed with a link, a one-line summary.'
    """
    today = date.today().isoformat()
    projects = get_projects(vault)

    lines = [
        "# 📚 Vault Index",
        f"> Auto-generated by Obsidian Second Mind. Last updated: {today}",
        "",
    ]

    # Global rules
    global_dir = vault / "_global"
    if global_dir.exists():
        global_notes = sorted(global_dir.rglob("*.md"))
        lines.append(f"## 🌐 Global Rules ({len(global_notes)})")
        lines.append("")
        for md in global_notes:
            note = parse_note(md, vault)
            if note:
                rel = md.relative_to(vault)
                lines.append(f"- [{note.title}]({rel}) — {note.note_type}")
        lines.append("")

    # Per-project sections
    total_notes = 0
    for project in projects:
        notes = get_project_notes(vault, project)
        if not notes:
            continue
        total_notes += len(notes)

        # Sort by type for consistent ordering
        type_order = {"prd": 0, "architecture": 1, "guidelines": 2, "api": 3,
                      "decision": 4, "concept": 5, "comparison": 6,
                      "synthesis": 7, "research": 8, "note": 9}
        notes.sort(key=lambda n: type_order.get(n.note_type, 99))

        types_list = ", ".join(sorted(set(n.note_type for n in notes)))
        lines.append(f"## 📁 {project} ({len(notes)} notes: {types_list})")
        lines.append("")
        for note in notes:
            rel = note.path
            # Extract first meaningful line as summary
            summary = _extract_summary(note.content)
            lines.append(f"- [{note.title}]({rel}) `{note.note_type}` — {summary}")
        lines.append("")

    # Stats
    lines.extend([
        "---",
        "## 📊 Stats",
        f"- Total projects: {len(projects)}",
        f"- Total notes: {total_notes}",
        f"- Last updated: {today}",
    ])

    index_path = vault / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Index regenerated: {total_notes} notes across {len(projects)} projects")


def _extract_summary(content: str, max_length: int = 80) -> str:
    """Extract a one-line summary from note content."""
    for line in content.split("\n"):
        line = line.strip()
        # Skip headings, empty lines, frontmatter
        if not line or line.startswith("#") or line.startswith("---"):
            continue
        # Skip metadata-like lines
        if line.startswith(">") or line.startswith("- **") or line.startswith("| "):
            continue
        # Clean up and truncate
        summary = line[:max_length]
        if len(line) > max_length:
            summary = summary.rsplit(" ", 1)[0] + "…"
        return summary
    return "(no summary)"


def _append_to_log(
    vault: Path,
    operation: str,
    project: str = "",
    title: str = "",
    note_type: str = "",
    tags: list[str] | None = None,
    details: str = "",
):
    """Append entry to log.md — chronological operation log.

    Karpathy: 'log.md is chronological. It's an append-only record of what
    happened and when — ingests, queries, lint passes.'
    """
    today = date.today().isoformat()
    now = datetime.now().strftime("%H:%M")

    log_path = vault / "log.md"

    # Create file with header if it doesn't exist
    if not log_path.exists():
        log_path.write_text(
            "# 📋 Vault Log\n"
            "> Chronological record of vault operations. Append-only.\n\n",
            encoding="utf-8",
        )

    # Build log entry
    parts = [f"## [{today} {now}] {operation}"]
    if project:
        parts[0] += f" | {project}"
    if title:
        parts[0] += f" | {title}"
    if note_type:
        parts.append(f"Type: {note_type}")
    if tags:
        parts.append(f"Tags: {', '.join(tags)}")
    if details:
        parts.append(details)
    parts.append("")  # Empty line after entry

    # Append to log
    with open(log_path, "a", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")

    logger.info(f"Log entry: {operation} | {project} | {title}")


# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------

@app.list_resources()
async def list_resources() -> list[Resource]:
    vault = _get_vault_path()
    projects = get_projects(vault)

    resources = [
        Resource(
            uri="vault://global",
            name="Global Rules & Standards",
            description="Global coding standards, tech stack, and design principles",
            mimeType="text/markdown",
        ),
        Resource(
            uri="vault://projects",
            name="All Projects",
            description="List of all projects in the vault",
            mimeType="application/json",
        ),
        Resource(
            uri="vault://index",
            name="Vault Index",
            description="Auto-generated catalog of all wiki pages",
            mimeType="text/markdown",
        ),
        Resource(
            uri="vault://log",
            name="Vault Log",
            description="Chronological operation log",
            mimeType="text/markdown",
        ),
    ]

    for project in projects:
        resources.append(Resource(
            uri=f"vault://project/{project}",
            name=f"Project: {project}",
            description=f"All notes for project '{project}'",
            mimeType="text/markdown",
        ))

    return resources


@app.read_resource()
async def read_resource(uri: str) -> str:
    vault = _get_vault_path()

    if uri == "vault://global":
        global_dir = vault / "_global"
        if not global_dir.exists():
            return "No global notes found."
        notes = []
        for md in sorted(global_dir.rglob("*.md")):
            note = parse_note(md, vault)
            if note:
                notes.append(f"# {note.title}\n\n{note.content}")
        return "\n\n---\n\n".join(notes)

    elif uri == "vault://projects":
        projects = get_projects(vault)
        result = {"projects": []}
        for p in projects:
            notes = get_project_notes(vault, p)
            result["projects"].append({
                "name": p,
                "notes_count": len(notes),
                "types": list(set(n.note_type for n in notes)),
            })
        return json.dumps(result, indent=2)

    elif uri == "vault://index":
        index_path = vault / "index.md"
        if index_path.exists():
            return index_path.read_text(encoding="utf-8")
        return "index.md not yet generated. Call create_note or rebuild_index to generate it."

    elif uri == "vault://log":
        log_path = vault / "log.md"
        if log_path.exists():
            return log_path.read_text(encoding="utf-8")
        return "log.md not yet created. Operations will be logged here automatically."

    elif uri.startswith("vault://project/"):
        project = uri.replace("vault://project/", "")
        notes = get_project_notes(vault, project)
        if not notes:
            return f"No notes found for project '{project}'."
        parts = []
        for note in notes:
            parts.append(f"## {note.title}\n**Type**: {note.note_type} | **Tags**: {', '.join(note.tags)}\n\n{note.content}")
        return "\n\n---\n\n".join(parts)

    return f"Unknown resource: {uri}"


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

@app.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="search_vault",
            description="Semantic search across the entire Obsidian vault. Use this to find relevant architecture decisions, guidelines, API rules, and business logic. Returns the most relevant chunks of text.",
            inputSchema={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Natural language search query, e.g. 'authentication flow' or 'UI design guidelines'",
                    },
                    "project": {
                        "type": "string",
                        "description": "Optional: filter by project slug (e.g. 'brieftube', 'faithly')",
                    },
                    "n_results": {
                        "type": "integer",
                        "description": "Number of results to return (default: 5)",
                        "default": 5,
                    },
                },
                "required": ["query"],
            },
        ),
        Tool(
            name="get_project_context",
            description="Get the full context for a specific project — PRD, architecture, rules, and guidelines. Use this when starting work on a project to understand its structure and rules.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug (e.g. 'brieftube', 'faithly')",
                    },
                },
                "required": ["project"],
            },
        ),
        Tool(
            name="get_global_rules",
            description="Get global coding standards, design principles, and tech stack that apply to ALL projects.",
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
        Tool(
            name="list_projects",
            description="List all projects in the Obsidian vault with their note counts.",
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
        Tool(
            name="get_note",
            description="Read a specific note by its path relative to the vault root.",
            inputSchema={
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Relative path to the note, e.g. 'brieftube/architecture.md'",
                    },
                },
                "required": ["path"],
            },
        ),
        Tool(
            name="create_note",
            description="Create a new note in the vault. Use this to document architecture decisions, add project guidelines, save research findings, create concept pages, or record comparisons and syntheses.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug for the note",
                    },
                    "title": {
                        "type": "string",
                        "description": "Note title",
                    },
                    "note_type": {
                        "type": "string",
                        "description": "Type of note: prd, architecture, guidelines, api, decision, note, concept, comparison, synthesis, research",
                        "enum": NOTE_TYPES,
                    },
                    "content": {
                        "type": "string",
                        "description": "Markdown content of the note",
                    },
                    "tags": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Tags for the note",
                    },
                },
                "required": ["project", "title", "note_type", "content"],
            },
        ),
        Tool(
            name="update_note",
            description="Update an existing note in the vault. Use to add Outcome sections to decisions, update architecture docs, or append new information. Supports both appending and full replacement.",
            inputSchema={
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Relative path to the note, e.g. 'brieftube/decisions.md'",
                    },
                    "append_content": {
                        "type": "string",
                        "description": "Content to append to the end of the note",
                    },
                    "replace_content": {
                        "type": "string",
                        "description": "Full replacement content (replaces entire body, keeps frontmatter)",
                    },
                },
                "required": ["path"],
            },
        ),
        Tool(
            name="lint_vault",
            description="Health-check the wiki. Finds: orphan pages (no inbound links), stale notes not updated for 90+ days, broken WikiLinks, frequently mentioned concepts without their own page, TODO/FIXME markers, and incomplete frontmatter.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Optional: lint only this project. If omitted, lints entire vault.",
                    },
                },
            },
        ),
        Tool(
            name="rebuild_index",
            description="Rebuild the vector search index and regenerate index.md. Use after manually editing vault files.",
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
        Tool(
            name="query_graph",
            description="Query the knowledge graph built from WikiLinks. Find connections between notes, hub pages, shortest paths, and clusters. Use to understand how concepts relate across projects.",
            inputSchema={
                "type": "object",
                "properties": {
                    "query_type": {
                        "type": "string",
                        "description": "Type of graph query",
                        "enum": ["neighbors", "path", "hubs", "clusters", "stats"],
                    },
                    "node": {
                        "type": "string",
                        "description": "Node name (note stem) for neighbors/path queries",
                    },
                    "target": {
                        "type": "string",
                        "description": "Target node for path queries",
                    },
                    "depth": {
                        "type": "integer",
                        "description": "Depth for neighbor traversal (default: 2)",
                        "default": 2,
                    },
                },
                "required": ["query_type"],
            },
        ),
        Tool(
            name="extract_patterns",
            description="Analyze decision outcomes across projects. Extract success patterns (best practices) and failure anti-patterns. Optionally generate auto-rules file in _global/auto-rules.md.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Optional: filter by project",
                    },
                    "generate_rules": {
                        "type": "boolean",
                        "description": "Generate auto-rules.md in vault (default: false)",
                        "default": False,
                    },
                },
            },
        ),
        # --- v0.5.0 Intelligence Layer ---
        Tool(
            name="analyze_sessions",
            description="Analyze session logs across projects to find repeating problems, common failure patterns, and reusable workarounds. Use this to identify areas that need better tooling or documentation.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Optional: analyze only this project's sessions",
                    },
                },
            },
        ),
        Tool(
            name="scout_tools",
            description="Scan the internet for new tools, MCP servers, and developer utilities relevant to our tech stack. Categories: 'mcp', 'ai', 'devtools', 'all'.",
            inputSchema={
                "type": "object",
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "Category to scan: 'mcp', 'ai', 'devtools', or 'all'",
                        "enum": ["mcp", "ai", "devtools", "all"],
                        "default": "all",
                    },
                },
            },
        ),
        Tool(
            name="check_dependencies",
            description="Check a project's dependencies (npm/pip/flutter) for outdated packages and security patches. Requires the project to exist on local filesystem.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug to check dependencies for",
                    },
                },
                "required": ["project"],
            },
        ),
        # --- v0.6.0: Capture & Recall ---
        Tool(
            name="get_wakeup_context",
            description="Get compact wake-up context (~200 tokens) with critical facts: "
                        "active projects, recent decisions, inbox items, blockers. "
                        "Call this FIRST when starting a new session for instant context.",
            inputSchema={
                "type": "object",
                "properties": {
                    "focus_project": {
                        "type": "string",
                        "description": "Optional: prioritize this project in the summary",
                    },
                },
            },
        ),
        Tool(
            name="save_insight",
            description="Save a valuable search answer or synthesis back into the wiki. "
                        "Use when a query produces insights worth preserving permanently. "
                        "Creates a compounding knowledge loop: sources → wiki → queries → insights → wiki.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug for the insight",
                    },
                    "title": {
                        "type": "string",
                        "description": "Title for the insight note",
                    },
                    "content": {
                        "type": "string",
                        "description": "The insight or synthesis to save",
                    },
                    "source_query": {
                        "type": "string",
                        "description": "The search query that led to this insight",
                    },
                    "note_type": {
                        "type": "string",
                        "enum": ["synthesis", "research", "concept"],
                        "default": "synthesis",
                        "description": "Type of insight note (default: synthesis)",
                    },
                },
                "required": ["project", "title", "content"],
            },
        ),
        # --- v0.7.0: Cascade Intelligence ---
        Tool(
            name="ingest_source",
            description="Cascade ingest: process a new source (text, URL, note) and "
                        "automatically update ALL related wiki pages. Creates primary note, "
                        "adds cross-references to related pages, creates concept stubs for "
                        "new entities. A single ingest can touch 5-15 wiki pages.",
            inputSchema={
                "type": "object",
                "properties": {
                    "content": {
                        "type": "string",
                        "description": "Source content (text, article, idea, etc.)",
                    },
                    "source_type": {
                        "type": "string",
                        "enum": ["text", "url", "note"],
                        "default": "text",
                        "description": "Type of source being ingested",
                    },
                    "project": {
                        "type": "string",
                        "default": "inbox",
                        "description": "Target project (default: inbox)",
                    },
                    "title": {
                        "type": "string",
                        "description": "Optional title for the note",
                    },
                    "url": {
                        "type": "string",
                        "description": "URL if source_type is 'url'",
                    },
                    "tags": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional tags for the note",
                    },
                },
                "required": ["content"],
            },
        ),
        Tool(
            name="auto_radar_scan",
            description="Run automated Tech Radar scan with diff tracking. Compares with "
                        "previous scan, saves diff report to vault, and optionally sends "
                        "Telegram alert if important new tools are found.",
            inputSchema={
                "type": "object",
                "properties": {
                    "category": {
                        "type": "string",
                        "enum": ["mcp", "ai", "devtools", "all"],
                        "default": "all",
                        "description": "Category to scan",
                    },
                    "notify": {
                        "type": "boolean",
                        "default": True,
                        "description": "Send Telegram alert for important findings (default: true)",
                    },
                },
            },
        ),
        # --- v0.8.0: Temporal Brain ---
        Tool(
            name="kg_add_fact",
            description="Add a temporal fact to the knowledge graph. Facts have validity windows "
                        "(valid_from/valid_to). Automatically detects contradictions with existing facts "
                        "and auto-resolves them by invalidating the old fact.",
            inputSchema={
                "type": "object",
                "properties": {
                    "subject": {
                        "type": "string",
                        "description": "Entity the fact is about (e.g. 'brieftube')",
                    },
                    "predicate": {
                        "type": "string",
                        "description": "Relationship type (e.g. 'uses_auth', 'uses_db', 'deploys_to')",
                    },
                    "object": {
                        "type": "string",
                        "description": "Value (e.g. 'clerk', 'postgresql', 'vercel')",
                    },
                    "source_note": {
                        "type": "string",
                        "description": "Path to the note establishing this fact",
                    },
                    "valid_from": {
                        "type": "string",
                        "description": "Date when fact became true (YYYY-MM-DD, default: today)",
                    },
                },
                "required": ["subject", "predicate", "object"],
            },
        ),
        Tool(
            name="kg_invalidate",
            description="Mark a fact as no longer valid. Use when a technology/approach has been replaced.",
            inputSchema={
                "type": "object",
                "properties": {
                    "subject": {"type": "string"},
                    "predicate": {"type": "string"},
                    "object": {"type": "string"},
                    "ended": {
                        "type": "string",
                        "description": "Date when fact stopped being true (YYYY-MM-DD, default: today)",
                    },
                },
                "required": ["subject", "predicate", "object"],
            },
        ),
        Tool(
            name="kg_timeline",
            description="Get chronological history of ALL facts about an entity, including expired ones. "
                        "Shows what was true when — tech stack evolution, decision history, etc.",
            inputSchema={
                "type": "object",
                "properties": {
                    "entity": {
                        "type": "string",
                        "description": "Entity to get timeline for (e.g. 'brieftube')",
                    },
                    "as_of": {
                        "type": "string",
                        "description": "Optional: query facts valid at this date (YYYY-MM-DD)",
                    },
                },
                "required": ["entity"],
            },
        ),
        Tool(
            name="kg_check_contradictions",
            description="Check the entire knowledge graph for contradictions — facts that conflict with each other. "
                        "Returns a report grouped by severity (critical/warning/info).",
            inputSchema={
                "type": "object",
                "properties": {},
            },
        ),
        # --- v0.9.0: Agent Memory ---
        Tool(
            name="save_session",
            description="Save current session context to vault for future recall. "
                        "Captures git state, uncommitted changes, recent commits, decisions, "
                        "and next steps. Creates both JSON snapshot and vault note. "
                        "Call this at the END of a session or before context loss.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug to save session for",
                    },
                    "summary": {
                        "type": "string",
                        "description": "Brief summary of what was done this session",
                    },
                    "next_steps": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Prioritized list of what to do next session",
                    },
                    "blockers": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Known blockers or issues",
                    },
                },
                "required": ["project"],
            },
        ),
        Tool(
            name="load_session",
            description="Load the most recent session snapshot for a project. "
                        "Returns git state, what was done, uncommitted changes, "
                        "next steps, and blockers. Use at session START for instant recall.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug to load last session for",
                    },
                },
                "required": ["project"],
            },
        ),
        Tool(
            name="get_enhanced_wakeup",
            description="Enhanced wake-up context combining standard context, last session memory, "
                        "and temporal KG facts. Use this instead of get_wakeup_context for "
                        "richer session start with full memory recall.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Focus project for enhanced context",
                    },
                },
            },
        ),
        # --- v1.1.0 Auto Architect ---
        Tool(
            name="scan_architecture",
            description="Scan a project's source code and generate an architecture map with "
                        "Mermaid dependency diagrams. Saves the map to vault as architecture-map.md. "
                        "Uses AST parsing — fast, no LLM needed.",
            inputSchema={
                "type": "object",
                "properties": {
                    "project": {
                        "type": "string",
                        "description": "Project slug to scan (must exist on local filesystem)",
                    },
                },
                "required": ["project"],
            },
        ),
    ]


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    vault = _get_vault_path()

    if name == "search_vault":
        index = _get_index()
        results = index.search(
            query=arguments["query"],
            n_results=arguments.get("n_results", 5),
            project=arguments.get("project"),
        )
        if not results:
            return [TextContent(type="text", text="No relevant results found.")]

        output_parts = []
        for i, r in enumerate(results, 1):
            method = r.get('search_method', '')
            method_badge = f" [{method}]" if method else ""
            output_parts.append(
                f"### Result {i} (score: {r['score']}{method_badge}) — {r['source']}\n"
                f"**Project**: {r['project']} | **Type**: {r['type']}\n\n"
                f"{r['text']}"
            )
        return [TextContent(type="text", text="\n\n---\n\n".join(output_parts))]

    elif name == "get_project_context":
        project = arguments["project"]
        notes = get_project_notes(vault, project)
        if not notes:
            return [TextContent(type="text", text=f"No notes found for project '{project}'.")]

        # Sort: prd first, then architecture, then rest
        type_order = {"prd": 0, "architecture": 1, "guidelines": 2, "api": 3,
                      "decision": 4, "concept": 5, "comparison": 6,
                      "synthesis": 7, "research": 8}
        notes.sort(key=lambda n: type_order.get(n.note_type, 99))

        parts = [f"# Project Context: {project}\n"]
        for note in notes:
            parts.append(f"## {note.title} ({note.note_type})\n\n{note.content}")

        return [TextContent(type="text", text="\n\n---\n\n".join(parts))]

    elif name == "get_global_rules":
        global_dir = vault / "_global"
        if not global_dir.exists():
            return [TextContent(type="text", text="No global rules found.")]
        notes = []
        for md in sorted(global_dir.rglob("*.md")):
            note = parse_note(md, vault)
            if note:
                notes.append(f"## {note.title}\n\n{note.content}")
        return [TextContent(type="text", text="\n\n---\n\n".join(notes))]

    elif name == "list_projects":
        projects = get_projects(vault)
        lines = ["# Projects in Vault\n"]
        for p in projects:
            notes = get_project_notes(vault, p)
            types = ", ".join(sorted(set(n.note_type for n in notes)))
            lines.append(f"- **{p}** — {len(notes)} notes ({types})")
        return [TextContent(type="text", text="\n".join(lines))]

    elif name == "get_note":
        note_path = (vault / arguments["path"]).resolve()
        if not note_path.is_relative_to(vault.resolve()):
            return [TextContent(type="text", text="❌ Path must be within vault.")]
        if not note_path.exists():
            return [TextContent(type="text", text=f"Note not found: {arguments['path']}")]
        note = parse_note(note_path, vault)
        if not note:
            return [TextContent(type="text", text="Failed to parse note.")]
        return [TextContent(type="text", text=f"# {note.title}\n\n{note.content}")]

    elif name == "create_note":
        project = arguments["project"]
        title = arguments["title"]
        note_type = arguments["note_type"]
        content = arguments["content"]
        tags = arguments.get("tags", [])

        # Create project directory if needed
        project_dir = vault / project
        project_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename (with collision protection)
        filename = title.lower().replace(" ", "-").replace("/", "-")
        filename = "".join(c for c in filename if c.isalnum() or c in "-_")
        file_path = project_dir / f"{filename}.md"
        counter = 1
        while file_path.exists():
            file_path = project_dir / f"{filename}-{counter}.md"
            counter += 1

        # Build frontmatter
        today = date.today().isoformat()
        fm_content = (
            f"---\n"
            f"project: {project}\n"
            f"type: {note_type}\n"
            f"tags:\n"
            + "".join(f"  - \"{tag}\"\n" for tag in tags)
            + f"priority: medium\n"
            f"created: {today}\n"
            f"updated: {today}\n"
            f"---\n\n"
            f"# {title}\n\n"
            f"{content}\n"
        )

        file_path.write_text(fm_content, encoding="utf-8")

        # Re-index this note
        index = _get_index()
        note = parse_note(file_path, vault)
        if note:
            index.index_notes([note])

        # Auto-log and regenerate index (Karpathy pattern)
        _append_to_log(vault, "create_note", project, title, note_type, tags)
        _regenerate_index(vault)

        result = f"✅ Note created: {file_path.relative_to(vault)}"

        # v0.8.0: Auto-extract temporal facts from decisions and architecture notes
        if note_type in ("decision", "architecture", "note", "research"):
            try:
                extractor = FactExtractor(vault)
                fact_report = extractor.extract_and_apply(
                    text=content,
                    project=project,
                    source_note=str(file_path.relative_to(vault)),
                    valid_from=today,
                )
                if fact_report.facts_added:
                    result += "\n\n" + fact_report.to_markdown()
            except Exception as e:
                logger.warning(f"Auto fact extraction failed: {e}")

        return [TextContent(type="text", text=result)]

    elif name == "update_note":
        note_path = (vault / arguments["path"]).resolve()
        if not note_path.is_relative_to(vault.resolve()):
            return [TextContent(type="text", text="❌ Path must be within vault.")]
        if not note_path.exists():
            return [TextContent(type="text", text=f"Note not found: {arguments['path']}")]

        import frontmatter as fm_lib
        raw = note_path.read_text(encoding="utf-8")
        post = fm_lib.loads(raw)

        if "replace_content" in arguments and arguments["replace_content"]:
            post.content = arguments["replace_content"]
        elif "append_content" in arguments and arguments["append_content"]:
            post.content = post.content.rstrip() + "\n\n" + arguments["append_content"]
        else:
            return [TextContent(type="text", text="No content provided. Use append_content or replace_content.")]

        # Update 'updated' field in frontmatter
        post.metadata["updated"] = date.today().isoformat()
        note_path.write_text(fm_lib.dumps(post), encoding="utf-8")

        # Re-index
        index = _get_index()
        note = parse_note(note_path, vault)
        if note:
            index.index_notes([note])

        # Auto-log
        _append_to_log(vault, "update_note", details=f"Updated: {arguments['path']}")
        _regenerate_index(vault)

        return [TextContent(type="text", text=f"✅ Note updated: {arguments['path']}")]

    elif name == "lint_vault":
        settings = get_settings()
        linter = VaultLinter(vault, stale_days=settings.lint_stale_days)
        report = linter.lint(project=arguments.get("project"))

        # Log the lint operation
        _append_to_log(
            vault, "lint",
            project=arguments.get("project", "all"),
            details=f"Found {len(report.issues)} issues "
                    f"(critical: {report.critical_count}, "
                    f"warning: {report.warning_count}, "
                    f"info: {report.info_count})",
        )

        return [TextContent(type="text", text=report.to_markdown())]

    elif name == "rebuild_index":
        index = _get_index()
        index.clear()
        notes = scan_vault(vault)
        stats = index.index_notes(notes)

        # Regenerate meta-files
        _regenerate_index(vault)
        _append_to_log(
            vault, "rebuild_index",
            details=f"Notes: {stats['added']}, Chunks: {stats['total_chunks']}",
        )

        return [TextContent(
            type="text",
            text=(
                f"✅ Index rebuilt:\n"
                f"- Notes indexed: {stats['added']}\n"
                f"- Total chunks: {stats['total_chunks']}\n"
                f"- index.md regenerated\n"
                f"- log.md updated\n"
            ),
        )]

    elif name == "query_graph":
        graph = KnowledgeGraph(vault)
        graph.build()
        query_type = arguments.get("query_type", "stats")

        if query_type == "stats":
            result = graph.to_markdown()
        elif query_type == "neighbors":
            node = arguments.get("node", "")
            if not node:
                return [TextContent(type="text", text="Node parameter required for neighbors query.")]
            data = graph.query_neighbors(node, depth=arguments.get("depth", 2))
            if "error" in data:
                result = f"❌ {data['error']}"
                if data.get("suggestions"):
                    result += f"\n\nDid you mean: {', '.join(data['suggestions'])}?"
            else:
                lines = [f"# Neighbors of: {data['info'].get('title', node)}", ""]
                for layer in data.get("layers", []):
                    lines.append(f"## Depth {layer['depth']} ({layer['count']} nodes)")
                    for n in layer["nodes"]:
                        lines.append(f"- {n['direction']} **{n['title']}** ({n['project']}) `{n['type']}`")
                    lines.append("")
                result = "\n".join(lines)
        elif query_type == "path":
            source = arguments.get("node", "")
            target = arguments.get("target", "")
            if not source or not target:
                return [TextContent(type="text", text="Both node and target required for path query.")]
            data = graph.find_path(source, target)
            if data.get("found"):
                path_str = " → ".join(p["title"] for p in data["path"])
                result = f"✅ Path found (length: {data['length']})\n\n{path_str}"
            else:
                result = f"❌ {data.get('message', data.get('error', 'No path found'))}"
        elif query_type == "hubs":
            stats = graph.get_stats()
            lines = ["# 🏛️ Hub Pages (Most Connected)", ""]
            for hub in stats.hubs:
                lines.append(f"- **{hub['title']}** ({hub['project']}) — {hub['degree']} connections")
            result = "\n".join(lines)
        elif query_type == "clusters":
            data = graph.get_clusters()
            lines = [f"# 🔮 Knowledge Clusters ({data['total_clusters']} projects)", ""]
            for cluster in data["clusters"]:
                lines.append(f"## {cluster['project']} ({cluster['node_count']} nodes, {cluster['total_connections']} connections)")
                for n in cluster["nodes"]:
                    lines.append(f"- **{n['title']}** `{n['type']}` — {n['connections']} links")
                lines.append("")
            result = "\n".join(lines)
        else:
            result = f"Unknown query_type: {query_type}"

        _append_to_log(vault, "query_graph", details=f"type={query_type}")
        return [TextContent(type="text", text=result)]

    elif name == "extract_patterns":
        extractor = PatternExtractor(vault)
        project = arguments.get("project")
        generate_rules = arguments.get("generate_rules", False)

        if generate_rules:
            rules = extractor.generate_auto_rules(project)
            _append_to_log(vault, "extract_patterns", details="Generated auto-rules.md")
            _regenerate_index(vault)
            return [TextContent(type="text", text=f"✅ Auto-rules generated:\n\n{rules}")]
        else:
            report = extractor.analyze(project)
            _append_to_log(vault, "extract_patterns", details=f"{report.total_decisions} decisions analyzed")
            return [TextContent(type="text", text=report.to_markdown())]

    # --- v0.5.0 Intelligence Layer ---

    elif name == "analyze_sessions":
        analyzer = SessionAnalyzer(vault)
        project = arguments.get("project")
        report = analyzer.analyze(project)
        _append_to_log(
            vault, "analyze_sessions",
            project=project or "all",
            details=f"{report.total_sessions} sessions, {report.total_issues} issues, "
                    f"{len(report.repeating_issues)} repeating patterns",
        )
        return [TextContent(type="text", text=report.to_markdown())]

    elif name == "scout_tools":
        radar = TechRadar(vault)
        category = arguments.get("category", "all")
        report = await radar.scan(category)
        _append_to_log(
            vault, "scout_tools",
            details=f"category={category}, found={report.tools_found}",
        )
        return [TextContent(type="text", text=report.to_markdown())]

    elif name == "check_dependencies":
        project = arguments["project"]
        settings = get_settings()
        # Build project path mapping from base dirs
        project_paths = {}
        for base_dir in settings.project_base_dirs:
            base = Path(base_dir)
            if base.exists():
                for d in base.iterdir():
                    if d.is_dir():
                        project_paths[d.name] = str(d)

        checker = DependencyChecker(vault, project_paths)
        report = await checker.check(project)
        _append_to_log(
            vault, "check_dependencies",
            project=project,
            details=f"manager={report.package_manager}, "
                    f"total={report.total_deps}, outdated={len(report.outdated)}",
        )
        return [TextContent(type="text", text=report.to_markdown())]

    elif name == "get_wakeup_context":
        settings = get_settings()
        wakeup = WakeupContext(
            vault_path=vault,
            project_base_dirs=settings.project_base_dirs,
        )
        context = wakeup.generate(
            focus_project=arguments.get("focus_project", ""),
        )
        _append_to_log(vault, "wakeup_context")
        return [TextContent(type="text", text=context)]

    elif name == "save_insight":
        project = arguments["project"]
        title = arguments["title"]
        content = arguments["content"]
        source_query = arguments.get("source_query", "")
        note_type = arguments.get("note_type", "synthesis")

        # Enrich content with write-back metadata
        enriched = content
        if source_query:
            enriched = f"> 🔄 Write-back from query: *{source_query}*\n\n{content}"

        # Create project directory if needed
        project_dir = vault / project
        project_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename
        filename = title.lower().replace(" ", "-").replace("/", "-")
        filename = "".join(c for c in filename if c.isalnum() or c in "-_")
        file_path = project_dir / f"{filename}.md"

        today = date.today().isoformat()
        tags = ["write-back", "insight"]
        if source_query:
            tags.append("query-derived")
        tags_yaml = "".join(f'  - "{tag}"\n' for tag in tags)

        fm_content = (
            f"---\n"
            f"project: {project}\n"
            f"type: {note_type}\n"
            f"tags:\n"
            f"{tags_yaml}"
            f"priority: medium\n"
            f"created: {today}\n"
            f"updated: {today}\n"
            f"source_query: \"{source_query}\"\n"
            f"---\n\n"
            f"# {title}\n\n"
            f"{enriched}\n"
        )

        file_path.write_text(fm_content, encoding="utf-8")

        # Re-index
        index = _get_index()
        note = parse_note(file_path, vault)
        if note:
            index.index_notes([note])

        _append_to_log(vault, "write-back", project, title, note_type, tags,
                       details=f"Query: {source_query}" if source_query else "")
        _regenerate_index(vault)

        return [TextContent(type="text", text=f"✅ Insight saved: {file_path.relative_to(vault)}")]

    # --- v0.7.0: Cascade Intelligence ---

    elif name == "ingest_source":
        content = arguments["content"]
        source_type = arguments.get("source_type", "text")
        project = arguments.get("project", "inbox")
        title = arguments.get("title", "")
        url = arguments.get("url", "")
        tags = arguments.get("tags", [])

        source = IngestSource(
            content=content,
            source_type=source_type,
            project=project,
            title=title,
            url=url,
            tags=tags,
        )

        index = _get_index()
        pipeline = IngestPipeline(vault_path=vault, index=index)
        report = pipeline.ingest(source)

        # v0.8.0: Auto-extract temporal facts
        try:
            extractor = FactExtractor(vault)
            fact_report = extractor.extract_and_apply(
                text=content,
                project=project,
                source_note=report.primary_note,
            )
        except Exception as e:
            logger.warning(f"Auto fact extraction during ingest failed: {e}")
            fact_report = None

        # Re-generate index.md
        _regenerate_index(vault)

        result = report.to_markdown()
        if fact_report and fact_report.facts_added:
            result += "\n" + fact_report.to_markdown()

        return [TextContent(type="text", text=result)]

    elif name == "auto_radar_scan":

        category = arguments.get("category", "all")
        should_notify = arguments.get("notify", True)

        auto_radar = AutoRadar(vault)
        diff = await auto_radar.run_scan(category)

        # Send Telegram notification if enabled and there are findings
        notification_status = ""
        if should_notify and diff.has_important_changes:
            settings = get_settings()
            if settings.telegram_bot_token and settings.telegram_allowed_users:
                sent = await radar_notify(
                    diff=diff,
                    bot_token=settings.telegram_bot_token,
                    chat_id=settings.telegram_allowed_users[0],
                )
                notification_status = "\n\n📱 Telegram alert sent!" if sent else "\n\n⚠️ Telegram alert failed."

        result = diff.to_markdown() + notification_status
        return [TextContent(type="text", text=result)]

    # --- v0.8.0: Temporal Brain ---

    elif name == "kg_add_fact":
        subject = arguments["subject"]
        predicate = arguments["predicate"]
        obj = arguments["object"]
        source_note = arguments.get("source_note", "")
        valid_from = arguments.get("valid_from", "")

        tkg = TemporalKnowledgeGraph(vault)
        fact, contradictions = tkg.add_fact(
            subject=subject,
            predicate=predicate,
            obj=obj,
            valid_from=valid_from,
            source_note=source_note,
        )

        result = f"✅ Fact added: {subject} {predicate} {obj} (since {fact.valid_from})"
        if contradictions:
            detector = ContradictionDetector(tkg)
            result += "\n\n" + detector.to_markdown(contradictions)

        return [TextContent(type="text", text=result)]

    elif name == "kg_invalidate":
        subject = arguments["subject"]
        predicate = arguments["predicate"]
        obj = arguments["object"]
        ended = arguments.get("ended", "")

        tkg = TemporalKnowledgeGraph(vault)
        found = tkg.invalidate(subject, predicate, obj, ended)

        if found:
            return [TextContent(type="text", text=f"✅ Fact invalidated: {subject} {predicate} {obj}")]
        else:
            return [TextContent(type="text", text=f"⚠️ Fact not found: {subject} {predicate} {obj}")]

    elif name == "kg_timeline":
        entity = arguments["entity"]
        as_of = arguments.get("as_of", "")

        tkg = TemporalKnowledgeGraph(vault)

        if as_of:
            # Query facts at specific date
            facts = tkg.query_entity(entity, as_of)
            lines = [f"# ⏱️ Facts about '{entity}' as of {as_of}", ""]
            for f in facts:
                status = "✅" if f.is_active else "❌"
                lines.append(f"{status} {f.predicate}: **{f.object}** (since {f.valid_from})")
        else:
            # Full timeline
            facts = tkg.timeline(entity)
            lines = [f"# ⏱️ Timeline: {entity}", ""]
            for f in facts:
                end = f" → {f.valid_to}" if f.valid_to else " → now"
                status = "✅" if f.is_active else "❌"
                lines.append(f"{status} [{f.valid_from}{end}] {f.predicate}: **{f.object}**")
                if f.source_note:
                    lines.append(f"  Source: `{f.source_note}`")

        if not facts:
            lines.append(f"No facts found for '{entity}'.")

        # Append stats
        lines.append("")
        lines.append(f"---\n{tkg.to_markdown()}")

        return [TextContent(type="text", text="\n".join(lines))]

    elif name == "kg_check_contradictions":
        tkg = TemporalKnowledgeGraph(vault)
        detector = ContradictionDetector(tkg)
        report = detector.to_markdown()
        return [TextContent(type="text", text=report)]

    # --- v0.9.0: Agent Memory ---

    elif name == "save_session":
        settings = get_settings()
        hooks = SessionHooks(vault, settings.project_base_dirs)
        snapshot = hooks.save_session(
            project=arguments["project"],
            summary=arguments.get("summary", ""),
            next_steps=arguments.get("next_steps"),
            blockers=arguments.get("blockers"),
        )

        result = (
            f"✅ Session saved for **{snapshot.project}** at {snapshot.timestamp}\n\n"
            f"{snapshot.to_markdown()}"
        )
        return [TextContent(type="text", text=result)]

    elif name == "load_session":
        settings = get_settings()
        hooks = SessionHooks(vault, settings.project_base_dirs)
        snapshot = hooks.load_last_session(arguments["project"])

        if not snapshot:
            return [TextContent(
                type="text",
                text=f"No saved session found for '{arguments['project']}'. "
                     f"This is the first session.",
            )]

        return [TextContent(type="text", text=snapshot.to_markdown())]

    elif name == "get_enhanced_wakeup":
        settings = get_settings()
        context = generate_enhanced_wakeup(
            vault_path=vault,
            project=arguments.get("project", ""),
            project_base_dirs=settings.project_base_dirs,
        )
        return [TextContent(type="text", text=context)]

    elif name == "scan_architecture":
        project = arguments["project"]
        settings = get_settings()
        result = scan_architecture(
            vault_path=vault,
            project=project,
            project_base_dirs=settings.project_base_dirs,
        )
        _append_to_log(vault, "scan_architecture", project=project)
        _regenerate_index(vault)
        return [TextContent(type="text", text=result)]

    return [TextContent(type="text", text=f"Unknown tool: {name}")]


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def run_server():
    """Run the MCP server via stdio."""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())


def main():
    """CLI entry point for the MCP server."""
    import asyncio
    asyncio.run(run_server())


if __name__ == "__main__":
    main()
